### ISSUE TITLE
[Chapter 12] Hardcoded /home/elspeth

### ISSUE THREAD

**Issue by RodrigoJacznik** [hjwp/Book-TDD-Web-Dev-Python#375]
Hi,

While reading the book, I came across an issue in one of the Ansible playbook examples. Here's the code in question:

```yaml
- name: Ensure db.sqlite3 file exists outside container
  ansible.builtin.file:
    path: /home/elspeth/db.sqlite3
    state: touch  

- name: Run container
  community.docker.docker_container:
    name: superlists
    image: superlists
    state: started
    recreate: true
    env_file: ~/superlists.env
    mounts:  
      - type: bind
        source: /home/elspeth/db.sqlite3
        target: /src/db.sqlite3
    ports: 80:8888

- name: Run migration inside container
  community.docker.docker_container_exec:  
    container: superlists
    command: ./manage.py migrate
```
ref: [https://github.com/hjwp/Book-TDD-Web-Dev-Python/blob/665e5be5e93de93d7c1f0d73ed2c25bd271b8427/chapter_12_ansible.asciidoc?plain=1#L998](https://github.com/hjwp/Book-TDD-Web-Dev-Python/blob/665e5be5e93de93d7c1f0d73ed2c25bd271b8427/chapter_12_ansible.asciidoc?plain=1#L998)

The problem is that the path `/home/elspeth/db.sqlite3` is hardcoded and assumes the username is `elspeth`. This could lead to issues when following along on systems where the username is different.

Suggested fix:
Instead of hardcoding the username, it would be better to use a variable like `{{ ansible_user }}` or another dynamic method to construct the home directory path, for example:

Thanks for the great book — it’s been really helpful so far!

**Comment by hjwp** [comment]
thanks so much!  I decided to use `{{ ansible_env.HOME }}`

```yaml
    - name: Ensure db.sqlite3 file exists outside container
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/db.sqlite3"
        state: touch
```

<img width="553" alt="Image" src="https://github.com/user-attachments/assets/dd22fbf1-59d0-49c5-9363-a4680158aba0" />


any other thoughts or suggestions on these deployment chapters?
